# Generated by Django 2.1.4 on 2019-01-04 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tnadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STPbetreiber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gvOuId', models.CharField(max_length=32, unique=True, verbose_name='gvOuId')),
                ('cn', models.CharField(help_text='Bezeichnung der Organisationseinheit (ausgeschrieben). (Abt. ITMS/Ref. NIK - \u2028Referat nationale und internationale Koordination)', max_length=64, verbose_name='Bezeichnung (cn)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingangsdatum')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'STPbetreiber',
                'verbose_name_plural': 'STPbetreiber',
                'db_table': 'tnadmin_gvorganisation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cacert', models.CharField(help_text='Issuer Certificate (TLS CA)', max_length=10000, unique=True, verbose_name='CA Certificate')),
                ('pvprole', models.CharField(choices=[('STP', 'STP'), ('AWP', 'AWP')], default='STP', max_length=3, null=True, verbose_name='Status')),
                ('subject_cn', models.CharField(help_text='Issuer X.509 SubjectCN (TLS CA)', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingangsdatum')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Namespaceobj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(help_text='fully qualified domain name or domain with * for any hostname, such as "*.sso.xyz.org"', max_length=30, unique=True, verbose_name='Namespace')),
                ('gvOuIdParent', models.ForeignKey(help_text='OrgID des Portalbetreibers', on_delete=django.db.models.deletion.PROTECT, to='fedop.STPbetreiber', verbose_name='gvOuId')),
            ],
            options={
                'verbose_name': 'FQDN Namespace',
                'verbose_name_plural': 'FQDN Namespaces',
                'ordering': ['fqdn'],
            },
        ),
        migrations.CreateModel(
            name='Revocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.CharField(help_text='X.509 cert PEM ohne Whitespace; Dieses Zertifikat darf nicht mehr in einem EntityDescriptor verwendet werden', max_length=10000, unique=True, verbose_name='Zertifikat')),
                ('subject_cn', models.CharField(default='', help_text='Issuer X.509 SubjectCN (TLS CA)', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Userprivilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.TextField(help_text='X.509 cert PEM ohen Whitespace', max_length=20000, unique=True, verbose_name='Portaladminsitrator-Zertifikat')),
                ('cn', models.CharField(blank=True, help_text='Vor- und Familienname des Zertifikatsinhabers', max_length=64, null=True, verbose_name='Name (cn)')),
                ('gvOuIdParent', models.ForeignKey(db_column='gvouid_parent', help_text='OrgID des Portalbetreibers', on_delete=django.db.models.deletion.PROTECT, to='tnadmin.GvUserPortalOperator')),
            ],
            options={
                'ordering': ['cn'],
            },
        ),
    ]
