# Generated by Django 2.1.4 on 2019-01-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_journal', models.TextField(help_text='Policy Journal signed with an enveloping XML signature', verbose_name='Policy Journal')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Änderungsdatum')),
            ],
            options={
                'verbose_name': 'Policy Journal',
                'verbose_name_plural': 'Policy Journal',
            },
        ),
    ]
