# Generated by Django 2.1.1 on 2018-12-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuer',
            old_name='subjectCN',
            new_name='subject_cn',
        ),
        migrations.AlterField(
            model_name='namespaceobj',
            name='gvOuIdParent',
            field=models.ForeignKey(help_text='OrgID des Portalbetreibers', on_delete=django.db.models.deletion.PROTECT, to='fedop.STPbetreiber', verbose_name='gvOuId'),
        ),
    ]
