# Generated by Django 2.1.1 on 2018-09-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testobj',
            new_name='Namespaceobj',
        ),
    ]
