# Generated by Django 2.1.1 on 2018-10-03 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fedop', '0002_auto_20180918_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 13, 33, 41, 769308, tzinfo=utc), verbose_name='Eingangsdatum'),
        ),
        migrations.AddField(
            model_name='issuer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='cacert',
            field=models.CharField(help_text='Issuer Certificate (TLS CA)', max_length=10000, unique=True, verbose_name='CA Certificate'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='pvprole',
            field=models.CharField(choices=[('STP', 'STP'), ('AWP', 'AWP')], default='STP', max_length=3, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='subjectCN',
            field=models.CharField(help_text='Issuer X.509 SubjectCN (TLS CA)', max_length=128),
        ),
    ]
