# Generated by Django 2.1.1 on 2018-12-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedop', '0002_auto_20181205_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='revocation',
            name='subject_cn',
            field=models.CharField(default='', help_text='Issuer X.509 SubjectCN (TLS CA)', max_length=128),
        ),
        migrations.AlterField(
            model_name='revocation',
            name='cert',
            field=models.CharField(help_text='X.509 cert PEM ohne Whitespace; Dieses Zertifikat darf nicht mehr in einem EntityDescriptor verwendet werden', max_length=10000, unique=True, verbose_name='Zertifikat'),
        ),
    ]
