# Generated by Django 2.1.4 on 2019-01-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedop', '0002_policyjournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GvOrg_PolicyJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gvouid', models.CharField(max_length=32)),
                ('cn', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'gvOrganisations used for Fedop/PMP. Each record is submitted to the Policy Journal',
            },
        ),
    ]
