# Generated by Django 2.1.1 on 2018-10-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedop', '0003_auto_20181003_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eingangsdatum'),
        ),
    ]
