# Generated by Django 2.1.4 on 2019-01-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedop', '0004_auto_20190131_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='marked4delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='namespaceobj',
            name='marked4delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revocation',
            name='marked4delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprivilege',
            name='marked4delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eingangsdatum'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Änderungsdatum'),
        ),
        migrations.AlterField(
            model_name='namespaceobj',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eingangsdatum'),
        ),
        migrations.AlterField(
            model_name='namespaceobj',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Änderungsdatum'),
        ),
        migrations.AlterField(
            model_name='revocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eingangsdatum'),
        ),
        migrations.AlterField(
            model_name='revocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Änderungsdatum'),
        ),
        migrations.AlterField(
            model_name='userprivilege',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eingangsdatum'),
        ),
        migrations.AlterField(
            model_name='userprivilege',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Änderungsdatum'),
        ),
    ]
