# Generated by Django 2.1.1 on 2018-10-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fedop', '0005_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namespaceobj',
            name='gvOuIdParent',
            field=models.ForeignKey(help_text='OrgID des Portalbetreibers', on_delete=django.db.models.deletion.PROTECT, to='fedop.Organization'),
        ),
    ]
