# Generated by Django 2.1.1 on 2018-10-03 17:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fedop', '0006_auto_20181003_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stpbetreiber',
            options={'verbose_name': 'STPbetreiber', 'verbose_name_plural': 'STPbetreiber'},
        ),
        migrations.AddField(
            model_name='stpbetreiber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Eingangsdatum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stpbetreiber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='namespaceobj',
            name='gvOuIdParent',
            field=models.ForeignKey(help_text='OrgID des Portalbetreibers', on_delete=django.db.models.deletion.PROTECT, to='fedop.STPbetreiber'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
