# Generated by Django 2.1.1 on 2018-10-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedop', '0007_auto_20181003_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivilege',
            name='cn',
            field=models.CharField(blank=True, help_text='Vor- und Familienname des Zertifikatsinhabers', max_length=64, null=True, verbose_name='Name (cn)'),
        ),
    ]
