# Generated by Django 2.1.1 on 2018-10-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedop', '0008_auto_20181003_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivilege',
            name='cert',
            field=models.TextField(help_text='X.509 cert PEM ohen Whitespace', max_length=20000, unique=True, verbose_name='Portaladminsitrator-Zertifikat'),
        ),
    ]
