LEGAL_BASIS_PVV = 'PVV'
LEGAL_BASIS_ENTITLED_ORG = 'PV-Zugriff'
LEGAL_BASIS_ENTITLED_ORG_PROCESSOR = 'PV-Zugriff-DL'
LEGAL_BASIS_PROCESSOR_IDP = 'PV-DL-STP'
LEGAL_BASIS_EXTERNAL_SP = 'Externer Anwendungsbetreiber'

LEGAL_BASIS_PARTICIPANT = (LEGAL_BASIS_PVV,
                           LEGAL_BASIS_ENTITLED_ORG,
                           LEGAL_BASIS_ENTITLED_ORG_PROCESSOR)
LEGAL_BASIS_IDP_OP = (LEGAL_BASIS_PVV,
                      LEGAL_BASIS_PROCESSOR_IDP)  # STP-Betreiber

LEGAL_BASIS_CHOICES = (
    (LEGAL_BASIS_PVV, LEGAL_BASIS_PVV),
    (LEGAL_BASIS_ENTITLED_ORG, LEGAL_BASIS_ENTITLED_ORG),
    (LEGAL_BASIS_PROCESSOR_IDP, LEGAL_BASIS_PROCESSOR_IDP),
    (LEGAL_BASIS_ENTITLED_ORG_PROCESSOR, LEGAL_BASIS_ENTITLED_ORG_PROCESSOR),
)
