# Generated by Django 2.1.4 on 2019-01-02 10:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GvFederation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_dn', models.CharField(default='', max_length=250)),
                ('gvStatus', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], db_column='gvStatus', default='active', max_length=8, null=True, verbose_name='Status')),
                ('gvSource', models.CharField(blank=True, db_column='gvSource', default='', max_length=100, null=True, verbose_name='Änderung am/durch')),
                ('gvScope', models.CharField(db_column='gvScope', default='gv.at', max_length=32, null=True)),
                ('gvFederationName', models.CharField(help_text='Eindeutige Bezeichnung der Federation im E-Mail-Adressen Format nach RFC 822 beziehungsweise als DNS Name. Das Zeichen SLASH darf nicht verwendet werden. Für den Portalverbund der österreichischen Behörden gem. Portalverbundvereinbarungist als gvFederationName der Wert portalverbund.gv.at festgelegt.Organisationsinterne Federations SOLLEN mit "internal@" + Namespace-Name der Organisation. (z.B. intern@lfrz.at) bezeichnet werden.', max_length=64, unique=True, verbose_name='Federation Name')),
                ('gvMetaDataURL', models.URLField(help_text='Bezugspunkt für Metadaten dieser Federation (URL für signiertes SAML Metadata Aggregat)', unique=True, verbose_name='Metadata URL')),
            ],
            options={
                'verbose_name': 'Federation',
                'verbose_name_plural': 'Federation',
            },
        ),
        migrations.CreateModel(
            name='GvFederationOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_dn', models.CharField(default='', max_length=250)),
                ('gvStatus', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], db_column='gvStatus', default='active', max_length=8, null=True, verbose_name='Status')),
                ('gvSource', models.CharField(blank=True, db_column='gvSource', default='', max_length=100, null=True, verbose_name='Änderung am/durch')),
                ('gvScope', models.CharField(db_column='gvScope', default='gv.at', max_length=32, null=True)),
                ('gvContractStatus', models.CharField(choices=[('PVV', 'PVV'), ('PV-Zugriff', 'PV-Zugriff'), ('PV-DL-STP', 'PV-DL-STP'), ('PV-Zugriff-DL', 'PV-Zugriff-DL')], max_length=30, verbose_name='Rechtsgrundlage')),
                ('gvDateEffective', models.DateField(default=datetime.date.today, verbose_name='Gültig Ab')),
                ('gvDateTerminated', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('gvCaseNumber', models.CharField(blank=True, help_text='Geschäftszahlen/Referenzen für Antrag, Vertrag und Änderungen', max_length=500, null=True, verbose_name='Ablagereferenz')),
                ('description', models.TextField(blank=True, help_text='Kommentare', max_length=10000, null=True)),
            ],
            options={
                'verbose_name': 'Federation Member',
                'verbose_name_plural': 'Federation Members',
                'ordering': ('gvOuId',),
            },
        ),
        migrations.CreateModel(
            name='GvOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_dn', models.CharField(default='', max_length=250)),
                ('gvStatus', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], db_column='gvStatus', default='active', max_length=8, null=True, verbose_name='Status')),
                ('gvSource', models.CharField(blank=True, db_column='gvSource', default='', max_length=100, null=True, verbose_name='Änderung am/durch')),
                ('gvScope', models.CharField(db_column='gvScope', default='gv.at', max_length=32, null=True)),
                ('gvOuVKZ', models.CharField(db_column='gvouvkz', help_text='Organisationskennzeichen (OKZ) gemäß der Spezifikation [VKZ]. Das Organisationskennzeichen ist für die Verwendung auf Ausdrucken, als Suchbegriff bzw. zur Anzeige vorgesehen. Das OKZ enthält Semantik und ist nur für österreichische Organisationen definiert. Für Referenzen in elektronischen Datenbeständen soll dieses Kennzeichen NICHT verwendet werden, sondern ausschließlich die gvOuId. Das VKZ kann aufgrund von Namensänderungen angepasst werden müssen. (z.B. BMEIA statt BMAA für das Außenministerium) \u2028(z.B. GGA-12345)', max_length=79, unique=True, validators=[django.core.validators.MaxLengthValidator(32, '"gvOuVKZ " Limit: 32 char')], verbose_name='Verwaltungskennz (gvOuVKZ)')),
                ('gvOuCn', models.CharField(db_column='gvoucn', help_text='Gesamtbezeichnung der Organisationseinheit für die Anschrift ohne Adressteil. (Bundesministerium für Inneres Sektion IV / Abt.ITMS / Ref.NIK)', max_length=1024, verbose_name='Gesamtbezeichnung (gvOuCn)')),
                ('gvNotValidBefore', models.CharField(blank=True, db_column='gvnotvalidbefore', help_text='JJJJ-MM-TT', max_length=10, null=True, verbose_name='gültig ab')),
                ('gvNotValidAfter', models.CharField(blank=True, db_column='gvnotvalidafter', help_text='Format JJJJ-MM-TT', max_length=10, null=True, verbose_name='gültig bis')),
                ('gvImageRef', models.CharField(default='', max_length=250)),
                ('gvLegalSuccessor', models.CharField(default='', max_length=250)),
                ('gvOtherID', models.CharField(default='', max_length=250)),
                ('gvOuId', models.CharField(default='', max_length=250)),
                ('gvOuIdParent', models.CharField(default='', max_length=250)),
                ('gvPhysicalAddress', models.CharField(default='', max_length=250)),
                ('gvSortkey', models.CharField(default='', max_length=250)),
                ('gvWebAddress', models.CharField(default='', max_length=250)),
                ('c', models.CharField(default='AT', max_length=250)),
                ('cn', models.CharField(help_text='Bezeichnung der Organisationseinheit (ausgeschrieben). (Abt. ITMS/Ref. NIK - \u2028Referat nationale und internationale Koordination)', max_length=120, verbose_name='Bezeichnung (cn)')),
                ('co', models.CharField(default='', max_length=250)),
                ('description', models.TextField(blank=True, help_text='Beschreibung', max_length=1024, null=True)),
                ('facsimileTelephoneNumber', models.CharField(default='', max_length=250)),
                ('l', models.CharField(blank=True, help_text='Ort', max_length=123, null=True, validators=[django.core.validators.MaxLengthValidator(64, '"l" Limit: 64 char')], verbose_name='Ort (l)')),
                ('mail', models.CharField(blank=True, help_text='RFC 822 [RFC882] E-Mail-Adresse \u2028(helpdesk@xyz.gv.at)', max_length=256, null=True)),
                ('ou', models.CharField(default='', max_length=250)),
                ('postalAddress', models.CharField(default='', max_length=250)),
                ('postalCode', models.CharField(default='', max_length=250)),
                ('postOfficeBox', models.CharField(default='', max_length=250)),
                ('street', models.CharField(default='', max_length=250)),
                ('telephoneNumber', models.CharField(default='', max_length=250)),
                ('o', models.CharField(help_text='Kurzbezeichnung der Organisation (z.B. BMI)', max_length=121, verbose_name='Kurzbezeichnung (o)')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisationen',
                'ordering': ['o'],
            },
        ),
        migrations.CreateModel(
            name='GvUserPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_dn', models.CharField(default='', max_length=250)),
                ('gvStatus', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], db_column='gvStatus', default='active', max_length=8, null=True, verbose_name='Status')),
                ('gvSource', models.CharField(blank=True, db_column='gvSource', default='', max_length=100, null=True, verbose_name='Änderung am/durch')),
                ('gvScope', models.CharField(db_column='gvScope', default='gv.at', max_length=32, null=True)),
                ('cn', models.CharField(help_text='Eindeutige Bezeichnung des Stammportals im Email-Format (pvpportal@noel.gv.at)', max_length=64, unique=True, verbose_name='Bezeichnung')),
                ('gvSamlIdpEntityId', models.URLField(blank=True, help_text='Eindeutiger Identifier des Stammportal in einer SAML Federation (URI)', max_length=80, null=True, verbose_name='EntityID')),
                ('gvMaxSecClass', models.PositiveIntegerField(help_text='Maximale gvSecClass, die Benutzer eines Portal erreichen können (z.B. 0). Anwendungsfälle sind vor allem Test- und Entwicklungsportale. ', validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Max Sicherheitsklasse')),
                ('description', models.TextField(blank=True, help_text='Beschreibung', max_length=1024, null=True)),
                ('gvPortalHotlineMail', models.TextField(blank=True, help_text='EMail-Adresse(n) Helpdesk', max_length=1024, null=True)),
                ('gvAdminContactName', models.TextField(blank=True, help_text='Name Portalverantwortlicher', max_length=1024, null=True)),
                ('gvAdminContactMail', models.TextField(blank=True, help_text='EMail-Adresse(n) Portalverantwortlicher', max_length=1024, null=True)),
                ('gvAdminContactTel', models.TextField(blank=True, help_text='Telefon Portalverantwortlicher', max_length=1024, null=True)),
                ('gvOuIdOwner', models.ForeignKey(blank=True, help_text='gvOuId des Stammportalbetreibers (Organisation des Portalverantwortlichen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='STPbetreiber', to='tnadmin.GvOrganisation', verbose_name='STPbetreiber')),
                ('gvOuIdParticipant', models.ManyToManyField(help_text='Liste der Participants, die am Stammportal berechtigt sind', to='tnadmin.GvOrganisation', verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Stammportal',
                'verbose_name_plural': 'Stammportale',
                'ordering': ('cn',),
            },
        ),
        migrations.CreateModel(
            name='LdapSyncError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_dn', models.CharField(max_length=222)),
                ('op', models.CharField(max_length=6)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='LdapSyncJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('add_upd_ldap_records_read', models.IntegerField(default=0)),
                ('add_upd_records_skipped', models.IntegerField(default=0)),
                ('add_upd_records_added', models.IntegerField(default=0)),
                ('add_upd_records_updated', models.IntegerField(default=0)),
                ('add_upd_records_update_failed', models.IntegerField(default=0)),
                ('del_db_records_read', models.IntegerField(default=0)),
                ('del_records_deleted', models.IntegerField(default=0)),
                ('del_records_delete_failed', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ldapsyncerror',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnadmin.LdapSyncJob'),
        ),
        migrations.AddField(
            model_name='gvfederationorg',
            name='gvCaseOrg',
            field=models.ForeignKey(blank=True, help_text='gvOuId der Organisation die den Antrag bearbeitet (i.A. der Depositar)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='BearbeiterOrganisation', to='tnadmin.GvOrganisation', verbose_name='Bearbeitende Organisation (VKZ)'),
        ),
        migrations.AddField(
            model_name='gvfederationorg',
            name='gvOuId',
            field=models.ForeignKey(help_text='gvOuId der Vertragspartei in der Rolle Teilnehmer, zugriffsberechtige Stelle oder Dienstleister', on_delete=django.db.models.deletion.CASCADE, related_name='Vertragspartei', to='tnadmin.GvOrganisation', verbose_name='Vertragspartei (berechtigt)'),
        ),
        migrations.AddField(
            model_name='gvfederationorg',
            name='gvOuId2',
            field=models.ForeignKey(blank=True, help_text='gvOuId der Vertragspartei in der Rolle "Vertreter des Depositars"', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VertragsparteiPVV', to='tnadmin.GvOrganisation', verbose_name='Vertragspartei (Aufsicht)'),
        ),
        migrations.AddField(
            model_name='gvfederationorg',
            name='gvOuId3',
            field=models.ForeignKey(blank=True, help_text='gvOuId des Dienstleister', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Dienstleister', to='tnadmin.GvOrganisation', verbose_name='Dienstleister'),
        ),
        migrations.CreateModel(
            name='GvParticipant',
            fields=[
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'proxy': True,
                'indexes': [],
            },
            bases=('tnadmin.gvfederationorg',),
        ),
        migrations.CreateModel(
            name='GvUserPortalOperator',
            fields=[
            ],
            options={
                'verbose_name': 'STP-Betreiber',
                'verbose_name_plural': 'STP-Betreiber',
                'proxy': True,
                'indexes': [],
            },
            bases=('tnadmin.gvfederationorg',),
        ),
    ]
