# Generated by Django 2.0.3 on 2018-03-21 22:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GvUFederationOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gvStatus', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], db_column='gvStatus', default='active', max_length=8, null=True, verbose_name='Status')),
                ('gvSource', models.CharField(blank=True, db_column='gvSource', default='', max_length=10, null=True, verbose_name='Änderung am/durch')),
                ('gvScope', models.CharField(db_column='gvScope', default='gv.at', max_length=32, null=True)),
                ('gvContractStatus', models.CharField(choices=[('PVV', 'PVV'), ('PV-Zugriff', 'PV-Zugriff'), ('PV-DL-STP', 'PV-DL-STP'), ('PV-Zugriff-DL', 'PV-Zugriff-DL')], max_length=30, verbose_name='Vertragsart')),
                ('gvDateEffective', models.DateField(default=datetime.date.today, verbose_name='Gültig Ab')),
                ('gvDateTerminated', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('gvCaseNumber', models.CharField(help_text='Geschäftszahl(en) für Antrag, Vertrag und Änderungen', max_length=500, verbose_name='Geschäftszahl(en)')),
                ('description', models.TextField(blank=True, help_text='Kommentare', max_length=10000, null=True)),
                ('gvCaseOrg', models.ForeignKey(blank=True, help_text='gvOuId der Organisation die den Antrag bearbeitet (i.A. der Depositar)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='BearbeiterOrganisation', to='tnadmin.GvOrganisation', verbose_name='gvOuId')),
                ('gvFederationNames', models.ForeignKey(blank=True, default='portalverbund.gv.at', help_text='Vertrag mit Federation', null=True, on_delete=django.db.models.deletion.CASCADE, to='tnadmin.GvFederation', verbose_name='gvOuId')),
                ('gvOuId', models.ForeignKey(blank=True, help_text='gvOuId der Organisation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vertragspartei', to='tnadmin.GvOrganisation', verbose_name='gvOuId')),
                ('gvUserPortalName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tnadmin.GvUserPortal', verbose_name='betroffenes Stammportal')),
            ],
            options={
                'verbose_name_plural': 'Federation Organisationen',
                'verbose_name': 'Federation Organisation',
            },
        ),
    ]
