# Generated by Django 2.1.4 on 2019-01-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE tnadmin_gvorganisation ADD CONSTRAINT gvOuVKZ_maxlen_32 CHECK (length(gvOuVKZ) <= 32);"
        ),
        migrations.RunSQL(
            "ALTER TABLE tnadmin_gvorganisation ADD CONSTRAINT l_maxlen_64 CHECK (length(l) <= 64);"
        ),
        migrations.RunSQL(
            "ALTER TABLE tnadmin_gvorganisation ADD CONSTRAINT cn_maxlen_64 CHECK (length(cn) <= 64);"
        ),
        migrations.RunSQL(
            "ALTER TABLE tnadmin_gvorganisation ADD CONSTRAINT o_maxlen_64 CHECK (length(o) <= 64);"
        ),
    ]
