# Generated by Django 2.1.4 on 2019-01-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE tnadmin_gvorganisation ADD CONSTRAINT lenchk_gvOuVKZ CHECK (length(gvOuVKZ) <= 32);"
            "ALTER TABLE tnadmin_gvorganisation DROP CONSTRAINT lenchk_gvOuVKZ;"
        ),
        migrations.RunSQL(
            "ALTER TABLE tnadmin_gvorganisation ADD CONSTRAINT lenchk_l CHECK (length(l) <= 64);"
            "ALTER TABLE tnadmin_gvorganisation DROP CONSTRAINT lenchk_l;"
        ),
        migrations.RunSQL(
            "ALTER TABLE tnadmin_gvorganisation ADD CONSTRAINT lenchk_cn CHECK (length(cn) <= 64);"
            "ALTER TABLE tnadmin_gvorganisation DROP CONSTRAINT lenchk_cn;"
        ),
        migrations.RunSQL(
            "ALTER TABLE tnadmin_gvorganisation ADD CONSTRAINT lenchk_o CHECK (length(o) <= 64);"
            "ALTER TABLE tnadmin_gvorganisation DROP CONSTRAINT lenchk_o;"
        ),
    ]
