# Generated by Django 2.1.4 on 2018-12-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gvorganisation',
            name='o',
            field=models.CharField(help_text='Kurzbezeichnung der Organisation (z.B. BMI)', max_length=64, verbose_name='Kurzbezeichnung (o)'),
        ),
    ]
