# Generated by Django 2.0.3 on 2018-03-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0002_gvufederationorg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GvUFederationOrg',
            new_name='GvFederationOrg',
        ),
    ]
