# Generated by Django 2.1.4 on 2019-01-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0002_custom_migr_add_constraints'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT  INTO tnadmin_gvfederation (gvfederationname, gvmetadataurl, gvScope) VALUES ('Verwaltungsportalverbund (Test)', 'http://mdfeed.test.portalverbund.gv.at/metadata.xml', 'initial');"
        ),
    ]
