# Generated by Django 2.1.4 on 2019-03-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0003_custom_migr_add_gvfederation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gvorganisation',
            name='cn',
            field=models.CharField(help_text='Bezeichnung der Organisationseinheit (ausgeschrieben). (Abt. ITMS/Ref. NIK - \u2028Referat nationale und internationale Koordination)', max_length=1024, verbose_name='Bezeichnung (cn)'),
        ),
    ]
