# Generated by Django 2.0.3 on 2018-03-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0004_auto_20180321_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gvuserportal',
            name='gvFederationNames',
        ),
        migrations.AddField(
            model_name='gvuserportal',
            name='gvAdminContactMail',
            field=models.TextField(blank=True, help_text='EMail-Adresse(n) Helpdesk', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='gvuserportal',
            name='gvAdminContactName',
            field=models.TextField(blank=True, help_text='EMail-Adresse(n) Helpdesk', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='gvuserportal',
            name='gvAdminContactTel',
            field=models.TextField(blank=True, help_text='EMail-Adresse(n) Helpdesk', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='gvuserportal',
            name='gvPortalHotlineMail',
            field=models.TextField(blank=True, help_text='EMail-Adresse(n) Helpdesk', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='gvfederationorg',
            name='gvCaseNumber',
            field=models.CharField(blank=True, help_text='Geschäftszahlen/Referenzen für Antrag, Vertrag und Änderungen', max_length=500, null=True, verbose_name='Ablagereferenz'),
        ),
        migrations.RemoveField(
            model_name='gvuserportal',
            name='gvOuIdParticipant',
        ),
        migrations.AddField(
            model_name='gvuserportal',
            name='gvOuIdParticipant',
            field=models.ManyToManyField(blank=True, help_text='Liste der zugriffsberechtigten Stelle (gvOrganisation), die das Stammportal benutzen, als gvOuId', null=True, to='tnadmin.GvOrganisation', verbose_name='Participant'),
        ),
    ]
