# Generated by Django 2.0.3 on 2018-03-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0005_auto_20180323_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvfederation',
            name='gvDefaultFederation',
            field=models.BooleanField(default=False, help_text='Setzt die Federation beim Erstellen einer Federation Organisation'),
        ),
        migrations.AlterField(
            model_name='gvorganisation',
            name='gvOuID',
            field=models.CharField(db_column='gvOuID', help_text='Format AT:VKZ, z.B. AT:L4', max_length=32, unique=True, verbose_name='Verwaltungskennz. (gvOuId)'),
        ),
        migrations.AlterField(
            model_name='gvorganisation',
            name='gvOuVKZ',
            field=models.CharField(db_column='gvOuVKZ', help_text='Organisationskennzeichen (OKZ) gemäß der Spezifikation [VKZ]. Das Organisationskennzeichen ist für die Verwendung auf Ausdrucken, als Suchbegriff bzw. zur Anzeige vorgesehen. Das OKZ enthält Semantik und ist nur für österreichische Organisationen definiert. Für Referenzen in elektronischen Datenbeständen soll dieses Kennzeichen NICHT verwendet werden, sondern ausschließlich die gvOuId. Das VKZ kann aufgrund von Namensänderungen angepasst werden müssen. (z.B. BMEIA statt BMAA für das Außenministerium) \u2028(z.B. GGA-12345)', max_length=32, unique=True, verbose_name='Organisationskennz.n (gvOuVKZ)'),
        ),
        migrations.AlterField(
            model_name='gvorgunit',
            name='gvOuID',
            field=models.CharField(db_column='gvOuID', help_text='Format AT:VKZ, z.B. AT:L4', max_length=32, unique=True, verbose_name='Verwaltungskennz. (gvOuId)'),
        ),
        migrations.AlterField(
            model_name='gvorgunit',
            name='gvOuVKZ',
            field=models.CharField(db_column='gvOuVKZ', help_text='Organisationskennzeichen (OKZ) gemäß der Spezifikation [VKZ]. Das Organisationskennzeichen ist für die Verwendung auf Ausdrucken, als Suchbegriff bzw. zur Anzeige vorgesehen. Das OKZ enthält Semantik und ist nur für österreichische Organisationen definiert. Für Referenzen in elektronischen Datenbeständen soll dieses Kennzeichen NICHT verwendet werden, sondern ausschließlich die gvOuId. Das VKZ kann aufgrund von Namensänderungen angepasst werden müssen. (z.B. BMEIA statt BMAA für das Außenministerium) \u2028(z.B. GGA-12345)', max_length=32, unique=True, verbose_name='Organisationskennz.n (gvOuVKZ)'),
        ),
        migrations.AlterField(
            model_name='gvuserportal',
            name='gvAdminContactMail',
            field=models.TextField(blank=True, help_text='EMail-Adresse(n) Portalverantwortlicher', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='gvuserportal',
            name='gvAdminContactName',
            field=models.TextField(blank=True, help_text='Name Portalverantwortlicher', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='gvuserportal',
            name='gvAdminContactTel',
            field=models.TextField(blank=True, help_text='Telefon Portalverantwortlicher', max_length=1024, null=True),
        ),
    ]
