# Generated by Django 2.0.3 on 2018-03-25 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0006_auto_20180325_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gvfederationorg',
            name='gvUserPortalName',
        ),
        migrations.AlterField(
            model_name='gvfederation',
            name='gvDefaultFederation',
            field=models.BooleanField(default=False, help_text='Setzt die Federation beim Erstellen einer Federation Organisation', verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='gvfederationorg',
            name='gvFederationNames',
            field=models.ForeignKey(help_text='Vertrag mit Federation', null=True, on_delete=django.db.models.deletion.CASCADE, to='tnadmin.GvFederation', verbose_name='Federation'),
        ),
    ]
