# Generated by Django 2.0.3 on 2018-03-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0007_auto_20180325_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='gvfederation',
            name='gvOuId',
            field=models.ForeignKey(blank=True, help_text='gvOuId des Depositars/Federation Operators', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Depositar', to='tnadmin.GvOrganisation', verbose_name='gvOuId'),
        ),
    ]
