# Generated by Django 2.0.3 on 2018-04-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0008_gvfederation_gvouid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GvParticipant',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name_plural': 'Participants',
                'proxy': True,
                'verbose_name': 'Participant',
            },
            bases=('tnadmin.gvfederationorg',),
        ),
        migrations.CreateModel(
            name='GvUserPortalOperator',
            fields=[
            ],
            options={
                'indexes': [],
                'verbose_name_plural': 'STP-Betreiber',
                'proxy': True,
                'verbose_name': 'STP-Betreiber',
            },
            bases=('tnadmin.gvfederationorg',),
        ),
        migrations.RemoveField(
            model_name='gvfederation',
            name='gvDefaultFederation',
        ),
        migrations.RemoveField(
            model_name='gvfederation',
            name='gvOuId',
        ),
        migrations.RemoveField(
            model_name='gvfederationorg',
            name='gvFederationNames',
        ),
        migrations.AlterField(
            model_name='gvfederationorg',
            name='gvCaseOrg',
            field=models.ForeignKey(blank=True, help_text='gvOuId der Organisation die den Antrag bearbeitet (i.A. der Depositar)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='BearbeiterOrganisation', to='tnadmin.GvOrganisation', verbose_name='Bearbeitende Organisation (VKZ)'),
        ),
        migrations.AlterField(
            model_name='gvfederationorg',
            name='gvContractStatus',
            field=models.CharField(choices=[('PVV', 'PVV'), ('PV-Zugriff', 'PV-Zugriff'), ('PV-DL-STP', 'PV-DL-STP'), ('PV-Zugriff-DL', 'PV-Zugriff-DL')], max_length=30, verbose_name='Rechtsgrundlage'),
        ),
        migrations.AlterField(
            model_name='gvfederationorg',
            name='gvOuId',
            field=models.ForeignKey(help_text='gvOuId der Vertragspartei in der Rolle Teilnehmer, zugriffsberechtige Stelle oder Dienstleister', on_delete=django.db.models.deletion.CASCADE, related_name='Vertragspartei', to='tnadmin.GvOrganisation', verbose_name='Vertragspartei'),
        ),
        migrations.AlterField(
            model_name='gvorganisation',
            name='gvOuID',
            field=models.CharField(db_column='gvOuID', help_text='Syntax: gvOuID::= Landeskennung ":" ID ID::= "VKZ:" VKZ | Org-Id  (z.B. AT:VKZ:GGA1234, AT:L9:9876)', max_length=32, unique=True, verbose_name='Organisationskennz. (gvOuId)'),
        ),
        migrations.AlterField(
            model_name='gvorganisation',
            name='gvOuVKZ',
            field=models.CharField(db_column='gvOuVKZ', help_text='Organisationskennzeichen (OKZ) gemäß der Spezifikation [VKZ]. Das Organisationskennzeichen ist für die Verwendung auf Ausdrucken, als Suchbegriff bzw. zur Anzeige vorgesehen. Das OKZ enthält Semantik und ist nur für österreichische Organisationen definiert. Für Referenzen in elektronischen Datenbeständen soll dieses Kennzeichen NICHT verwendet werden, sondern ausschließlich die gvOuId. Das VKZ kann aufgrund von Namensänderungen angepasst werden müssen. (z.B. BMEIA statt BMAA für das Außenministerium) \u2028(z.B. GGA-12345)', max_length=32, unique=True, verbose_name='Verwaltungskennz (gvOuVKZ)'),
        ),
        migrations.AlterField(
            model_name='gvorgunit',
            name='gvOuID',
            field=models.CharField(db_column='gvOuID', help_text='Syntax: gvOuID::= Landeskennung ":" ID ID::= "VKZ:" VKZ | Org-Id  (z.B. AT:VKZ:GGA1234, AT:L9:9876)', max_length=32, unique=True, verbose_name='Organisationskennz. (gvOuId)'),
        ),
        migrations.AlterField(
            model_name='gvorgunit',
            name='gvOuVKZ',
            field=models.CharField(db_column='gvOuVKZ', help_text='Organisationskennzeichen (OKZ) gemäß der Spezifikation [VKZ]. Das Organisationskennzeichen ist für die Verwendung auf Ausdrucken, als Suchbegriff bzw. zur Anzeige vorgesehen. Das OKZ enthält Semantik und ist nur für österreichische Organisationen definiert. Für Referenzen in elektronischen Datenbeständen soll dieses Kennzeichen NICHT verwendet werden, sondern ausschließlich die gvOuId. Das VKZ kann aufgrund von Namensänderungen angepasst werden müssen. (z.B. BMEIA statt BMAA für das Außenministerium) \u2028(z.B. GGA-12345)', max_length=32, unique=True, verbose_name='Verwaltungskennz (gvOuVKZ)'),
        ),
        migrations.AlterField(
            model_name='gvuserportal',
            name='gvOuIdParticipant',
            field=models.ManyToManyField(help_text='Liste der Participants, die am Stammportal berechtigt sind', to='tnadmin.GvOrganisation', verbose_name='Participant'),
        ),
    ]
