# Generated by Django 2.0.3 on 2018-04-17 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0009_auto_20180417_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gvfederationorg',
            options={'verbose_name': 'Federation Member', 'verbose_name_plural': 'Federation Members'},
        ),
        migrations.AddField(
            model_name='gvfederationorg',
            name='gvOuId2',
            field=models.ForeignKey(blank=True, help_text='gvOuId der Vertragspartei in der Rolle "Vertreter des Depositars"', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VertragsparteiPVV', to='tnadmin.GvOrganisation', verbose_name='Vertragspartei'),
        ),
    ]
