# Generated by Django 2.0.3 on 2018-04-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnadmin', '0010_auto_20180417_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gvfederationorg',
            name='gvOuId',
            field=models.ForeignKey(help_text='gvOuId der Vertragspartei in der Rolle Teilnehmer, zugriffsberechtige Stelle oder Dienstleister', on_delete=django.db.models.deletion.CASCADE, related_name='Vertragspartei', to='tnadmin.GvOrganisation', verbose_name='Vertragspartei (berechtigt)'),
        ),
        migrations.AlterField(
            model_name='gvfederationorg',
            name='gvOuId2',
            field=models.ForeignKey(blank=True, help_text='gvOuId der Vertragspartei in der Rolle "Vertreter des Depositars"', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VertragsparteiPVV', to='tnadmin.GvOrganisation', verbose_name='Vertragspartei (Aufsicht)'),
        ),
    ]
