# Generated by Django 2.1.4 on 2019-01-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MDstatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Admin Notiz')),
                ('content_valid', models.BooleanField(default=False, verbose_name='Content validation')),
                ('deletionRequest', models.BooleanField(default=False, null=True, verbose_name='Deletion Request (unpublish Entity)')),
                ('ed_file_upload', models.FileField(blank=True, default='', null=True, upload_to='portaladmin', verbose_name='EntityDescriptor hochladen')),
                ('ed_signed', models.TextField(blank=True, help_text='SAML EntityDescriptor (signiert)', max_length=100000, null=True, verbose_name='EntityDescriptor signiert')),
                ('ed_uploaded', models.TextField(help_text='SAML EntityDescriptor (geladen, nicht signiert)', max_length=100000, verbose_name='EntityDescriptor hochgeladen')),
                ('ed_uploaded_filename', models.CharField(default=None, max_length=100, null=True, verbose_name='Upload Filename')),
                ('entityID', models.CharField(blank=True, max_length=300, null=True)),
                ('entity_fqdn', models.CharField(blank=True, max_length=300, null=True, verbose_name='Entity FQDN')),
                ('make_blank_entityid_unique', models.CharField(blank=True, max_length=16, null=True, verbose_name='if the entityID is blank due to a validation error, this hash value assures that the unique constraint is not violated')),
                ('operation', models.CharField(blank=True, max_length=7, null=True)),
                ('org_cn', models.CharField(blank=True, max_length=60, null=True, verbose_name='Organization')),
                ('org_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='OrgID')),
                ('signer_authorized', models.BooleanField(default=False, null=True, verbose_name='Signer Authorization')),
                ('signer_subject', models.CharField(blank=True, max_length=80, null=True, verbose_name='Signator')),
                ('status', models.CharField(choices=[('created', 'erstellt'), ('uploaded', 'hochgeladen'), ('signed', 'signiert'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('accepted', 'akzeptiert')], default='created', max_length=14, verbose_name='Workflow Status')),
                ('statusgroup', models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend')], max_length=8, verbose_name='Status Group')),
                ('validation_message', models.TextField(blank=True, max_length=100000, null=True, verbose_name='Error Messages')),
                ('namespace', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingangsdatum')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Änderungsdatum')),
            ],
            options={
                'verbose_name': 'Metadaten Statement',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='mdstatement',
            unique_together={('entityID', 'make_blank_entityid_unique', 'statusgroup')},
        ),
    ]
