# Generated by Django 2.1.1 on 2018-12-03 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fedop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MDstatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Admin Notiz')),
                ('content_valid', models.BooleanField(default=False, verbose_name='Content validation')),
                ('deletionRequest', models.BooleanField(default=False, null=True, verbose_name='Deletion Request (unpublish Entity)')),
                ('ed_file_upload', models.FileField(blank=True, default='', null=True, upload_to='upload/', verbose_name='EntityDescriptor hochladen')),
                ('ed_signed', models.TextField(blank=True, help_text='SAML EntityDescriptor (signiert)', max_length=100000, null=True, verbose_name='EntityDescriptor signiert')),
                ('ed_uploaded', models.TextField(help_text='SAML EntityDescriptor (geladen, nicht signiert)', max_length=100000, verbose_name='EntityDescriptor hochgeladen')),
                ('ed_uploaded_filename', models.CharField(default=None, max_length=100, null=True, verbose_name='Upload Filename')),
                ('entityID', models.CharField(blank=True, max_length=300, null=True)),
                ('entity_fqdn', models.CharField(blank=True, max_length=300, null=True, verbose_name='Entity FQDN')),
                ('make_blank_entityid_unique', models.CharField(blank=True, max_length=16, null=True, verbose_name='if the entityID is blank due to a validation error, this hash value assures that the unique constraint is not violated')),
                ('operation', models.CharField(blank=True, max_length=7, null=True)),
                ('org_cn', models.CharField(blank=True, max_length=60, null=True, verbose_name='Organization')),
                ('org_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='OrgID')),
                ('signer_authorized', models.BooleanField(default=False, null=True, verbose_name='Signer Authorization')),
                ('signer_subject', models.CharField(blank=True, max_length=80, null=True, verbose_name='Signator')),
                ('status', models.CharField(choices=[('created', 'erstellt'), ('uploaded', 'hochgeladen'), ('signed', 'signiert'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('accepted', 'akzeptiert')], default='created', max_length=14, verbose_name='Workflow Status')),
                ('statusgroup', models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend')], max_length=8, verbose_name='Status Group')),
                ('validation_message', models.TextField(blank=True, max_length=100000, null=True, verbose_name='Error Messages')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingangsdatum')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Änderungsdatum')),
                ('checkout_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='md_statements', to='portaladmin.CheckOut')),
                ('namespace', models.ForeignKey(blank=True, help_text='Namespace', null=True, on_delete=django.db.models.deletion.PROTECT, to='fedop.Namespaceobj')),
            ],
            options={
                'ordering': ['-updated_at'],
                'verbose_name': 'Metadaten Statement',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MDstatementHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Admin Notiz')),
                ('content_valid', models.BooleanField(default=False, verbose_name='Content validation')),
                ('deletionRequest', models.BooleanField(default=False, null=True, verbose_name='Deletion Request (unpublish Entity)')),
                ('ed_file_upload', models.FileField(blank=True, default='', null=True, upload_to='upload/', verbose_name='EntityDescriptor hochladen')),
                ('ed_signed', models.TextField(blank=True, help_text='SAML EntityDescriptor (signiert)', max_length=100000, null=True, verbose_name='EntityDescriptor signiert')),
                ('ed_uploaded', models.TextField(help_text='SAML EntityDescriptor (geladen, nicht signiert)', max_length=100000, verbose_name='EntityDescriptor hochgeladen')),
                ('ed_uploaded_filename', models.CharField(default=None, max_length=100, null=True, verbose_name='Upload Filename')),
                ('entityID', models.CharField(blank=True, max_length=300, null=True)),
                ('entity_fqdn', models.CharField(blank=True, max_length=300, null=True, verbose_name='Entity FQDN')),
                ('make_blank_entityid_unique', models.CharField(blank=True, max_length=16, null=True, verbose_name='if the entityID is blank due to a validation error, this hash value assures that the unique constraint is not violated')),
                ('operation', models.CharField(blank=True, max_length=7, null=True)),
                ('org_cn', models.CharField(blank=True, max_length=60, null=True, verbose_name='Organization')),
                ('org_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='OrgID')),
                ('signer_authorized', models.BooleanField(default=False, null=True, verbose_name='Signer Authorization')),
                ('signer_subject', models.CharField(blank=True, max_length=80, null=True, verbose_name='Signator')),
                ('status', models.CharField(choices=[('created', 'erstellt'), ('uploaded', 'hochgeladen'), ('signed', 'signiert'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('accepted', 'akzeptiert')], default='created', max_length=14, verbose_name='Workflow Status')),
                ('statusgroup', models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend')], max_length=8, verbose_name='Status Group')),
                ('validation_message', models.TextField(blank=True, max_length=100000, null=True, verbose_name='Error Messages')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingangsdatum')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Änderungsdatum')),
                ('MDstatement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaladmin.MDstatement')),
                ('namespace', models.ForeignKey(blank=True, help_text='Namespace', null=True, on_delete=django.db.models.deletion.PROTECT, to='fedop.Namespaceobj')),
            ],
            options={
                'verbose_name_plural': 'Metadaten Statements History',
                'verbose_name': 'Metadaten Statement History',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mdstatement',
            unique_together={('entityID', 'make_blank_entityid_unique', 'statusgroup')},
        ),
    ]
