# Generated by Django 2.1.1 on 2018-09-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MDstatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityID', models.CharField(max_length=128, unique=True)),
                ('Status', models.CharField(choices=[('uploaded', 'uploaded'), ('request_queue', 'request_queue'), ('rejected', 'rejected'), ('published', 'published')], default='uploaded', max_length=14, null=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eingangsdatum')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metadata Statement',
                'ordering': ['entityID'],
            },
        ),
    ]
