# Generated by Django 2.1.1 on 2018-12-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='checkout_by',
        ),
        migrations.RemoveField(
            model_name='mdstatementhistory',
            name='MDstatement',
        ),
        migrations.RemoveField(
            model_name='mdstatementhistory',
            name='namespace',
        ),
        migrations.RemoveField(
            model_name='mdstatement',
            name='checkout_status',
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='ed_file_upload',
            field=models.FileField(blank=True, default='', null=True, upload_to='portaladmin', verbose_name='EntityDescriptor hochladen'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='namespace',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='CheckOut',
        ),
        migrations.DeleteModel(
            name='MDstatementHistory',
        ),
    ]
