# Generated by Django 2.1.4 on 2019-03-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdstatement',
            name='allow_selfsigned',
            field=models.BooleanField(default=False, help_text='Selbst-signiertes oder nicht registriertes Zertifikat nur für PVP-S-Profil', verbose_name='Selbst-signiertes Zertifikat OK'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='ed_uploaded',
            field=models.TextField(default='', help_text='SAML EntityDescriptor (geladen, nicht signiert)', max_length=100000, verbose_name='EntityDescriptor hochgeladen'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='entityID',
            field=models.CharField(blank=True, default='', max_length=301, null=True),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='make_blank_entityid_unique',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='if the entityID is blank due to a validation error, this hash value assures that the unique constraint is not violated'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='statusgroup',
            field=models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend')], default='frontend', max_length=8, verbose_name='Status Group'),
        ),
    ]
