# Generated by Django 2.1.1 on 2018-10-04 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdstatement',
            options={'ordering': ['entityID'], 'verbose_name': 'Metadaten Statement'},
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='Validation_message',
            field=models.CharField(default=datetime.datetime(2018, 10, 4, 18, 13, 6, 539163, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='delete',
            field=models.BooleanField(default=False, help_text='EntitiyDescriptor vom Metadaten Aggregat löschen'),
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='ed_signed',
            field=models.TextField(default=datetime.datetime(2018, 10, 4, 18, 13, 21, 939333, tzinfo=utc), help_text='SAML EntityDescriptor (signiert)', max_length=100000, verbose_name='EntityDescriptor signiert'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='ed_uploaded',
            field=models.TextField(default=datetime.datetime(2018, 10, 4, 18, 13, 33, 851617, tzinfo=utc), help_text='SAML EntityDescriptor (uploaded, signiert)', max_length=100000, verbose_name='EntityDescriptor uploaded'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='Status',
            field=models.CharField(choices=[('uploaded', 'hochgeladen'), ('invalid', 'Validierungsfehler'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('published', 'veröffentlicht')], default='uploaded', max_length=14, null=True, verbose_name='Status'),
        ),
    ]
