# Generated by Django 2.1.4 on 2019-01-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdstatement',
            name='ed_uploaded_filename',
            field=models.CharField(default=None, max_length=257, null=True, verbose_name='Upload Filename'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='entityID',
            field=models.CharField(blank=True, max_length=301, null=True),
        ),
    ]
