# Generated by Django 2.1.1 on 2018-10-18 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0003_auto_20181009_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='Status',
            field=models.CharField(choices=[('uploaded', 'hochgeladen'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('published', 'veröffentlicht'), ('deleted', 'gelöscht')], default='uploaded', max_length=14, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='checkout_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='md_statements', to='portaladmin.CheckOut'),
        ),
    ]
