# Generated by Django 2.1.1 on 2018-10-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0004_auto_20181018_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdstatement',
            name='Validation_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='ed_signed',
            field=models.TextField(blank=True, help_text='SAML EntityDescriptor (signiert)', max_length=100000, null=True, verbose_name='EntityDescriptor signiert'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='ed_uploaded',
            field=models.TextField(blank=True, help_text='SAML EntityDescriptor (uploaded, signiert)', max_length=100000, null=True, verbose_name='EntityDescriptor uploaded'),
        ),
    ]
