# Generated by Django 2.1.1 on 2018-11-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0007_auto_20181101_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdstatement',
            options={'ordering': ['updated_at'], 'verbose_name': 'Metadaten Statement'},
        ),
        migrations.RenameField(
            model_name='mdstatement',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='mdstatementhistory',
            old_name='Status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='mdstatement',
            name='entityID',
        ),
        migrations.RemoveField(
            model_name='mdstatement',
            name='validation_message',
        ),
        migrations.RemoveField(
            model_name='mdstatementhistory',
            name='entityID',
        ),
        migrations.RemoveField(
            model_name='mdstatementhistory',
            name='validation_message',
        ),
    ]
