# Generated by Django 2.1.1 on 2018-11-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0008_auto_20181102_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdstatementhistory',
            options={'verbose_name': 'Metadaten Statement History', 'verbose_name_plural': 'Metadaten Statements History'},
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='validation_status',
            field=models.CharField(choices=[('valid', 'gültig'), ('not valid', 'nicht gültig')], default='?', max_length=14, null=True, verbose_name='Validierung'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='validation_status',
            field=models.CharField(choices=[('valid', 'gültig'), ('not valid', 'nicht gültig')], default='?', max_length=14, null=True, verbose_name='Validierung'),
        ),
    ]
