# Generated by Django 2.1.1 on 2018-11-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0009_auto_20181102_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdstatement',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='mdstatement',
            name='validation_status',
        ),
        migrations.RemoveField(
            model_name='mdstatementhistory',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='mdstatementhistory',
            name='validation_status',
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='admin_note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Portaladmin Notiz'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='admin_note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Portaladmin Notiz'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='ed_uploaded',
            field=models.TextField(blank=True, help_text='SAML EntityDescriptor (geladen, nicht signiert)', max_length=100000, null=True, verbose_name='EntityDescriptor geladen'),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='ed_uploaded',
            field=models.TextField(blank=True, help_text='SAML EntityDescriptor (geladen, nicht signiert)', max_length=100000, null=True, verbose_name='EntityDescriptor geladen'),
        ),
    ]
