# Generated by Django 2.1.1 on 2018-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0010_auto_20181108_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdstatement',
            name='ed_file_upload',
            field=models.FileField(default='', upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='ed_file_upload',
            field=models.FileField(default='', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='admin_note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Admin Notiz'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='status',
            field=models.CharField(choices=[('created', 'erstellt'), ('uploaded', 'hochgeladen'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('accepted', 'akzeptiert')], default='created', max_length=14, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='admin_note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Admin Notiz'),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='status',
            field=models.CharField(choices=[('created', 'erstellt'), ('uploaded', 'hochgeladen'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('accepted', 'akzeptiert')], default='created', max_length=14, null=True, verbose_name='Status'),
        ),
    ]
