# Generated by Django 2.1.1 on 2018-11-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0011_auto_20181108_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdstatement',
            name='ed_uploaded_filename',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Upload Filename'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='ed_uploaded_filename',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Upload Filename'),
        ),
    ]
