# Generated by Django 2.1.1 on 2018-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0012_auto_20181108_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdstatement',
            name='entityID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='entityID',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='ed_file_upload',
            field=models.FileField(blank=True, default='', null=True, upload_to='upload/', verbose_name='EntityDescriptor hochladen'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='ed_uploaded',
            field=models.TextField(blank=True, help_text='SAML EntityDescriptor (geladen, nicht signiert)', max_length=100000, null=True, verbose_name='EntityDescriptor hochgeladen'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='status',
            field=models.CharField(choices=[('created', 'erstellt'), ('uploaded', 'hochgeladen'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('accepted', 'akzeptiert')], default='created', max_length=14, null=True, verbose_name='Workflow Status'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Änderungsdatum'),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='ed_file_upload',
            field=models.FileField(blank=True, default='', null=True, upload_to='upload/', verbose_name='EntityDescriptor hochladen'),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='ed_uploaded',
            field=models.TextField(blank=True, help_text='SAML EntityDescriptor (geladen, nicht signiert)', max_length=100000, null=True, verbose_name='EntityDescriptor hochgeladen'),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='status',
            field=models.CharField(choices=[('created', 'erstellt'), ('uploaded', 'hochgeladen'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('accepted', 'akzeptiert')], default='created', max_length=14, null=True, verbose_name='Workflow Status'),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Änderungsdatum'),
        ),
    ]
