# Generated by Django 2.1.1 on 2018-11-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0013_auto_20181125_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdstatement',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Metadaten Statement'},
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='content_valid',
            field=models.BooleanField(default=False, verbose_name='Content validation'),
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='deletionRequest',
            field=models.BooleanField(default=False, verbose_name='Deletion Request (unpublish Entity)'),
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='org_cn',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='org_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='OrgID'),
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='signer_authorized',
            field=models.BooleanField(default=False, verbose_name='Signer Authorization'),
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='signer_subject',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Signator'),
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='validation_message',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Error Messages'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='content_valid',
            field=models.BooleanField(default=False, verbose_name='Content validation'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='deletionRequest',
            field=models.BooleanField(default=False, verbose_name='Deletion Request (unpublish Entity)'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='org_cn',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='org_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='OrgID'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='signer_authorized',
            field=models.BooleanField(default=False, verbose_name='Signer Authorization'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='signer_subject',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Signator'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='validation_message',
            field=models.TextField(blank=True, max_length=100000, null=True, verbose_name='Error Messages'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='status',
            field=models.CharField(choices=[('created', 'erstellt'), ('uploaded', 'hochgeladen'), ('signed', 'signiert'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('accepted', 'akzeptiert')], default='created', max_length=14, null=True, verbose_name='Workflow Status'),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='status',
            field=models.CharField(choices=[('created', 'erstellt'), ('uploaded', 'hochgeladen'), ('signed', 'signiert'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('accepted', 'akzeptiert')], default='created', max_length=14, null=True, verbose_name='Workflow Status'),
        ),
    ]
