# Generated by Django 2.1.1 on 2018-11-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0015_auto_20181129_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdstatement',
            name='entity_fqdn',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='entity_fqdn',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
