# Generated by Django 2.1.1 on 2018-11-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0016_auto_20181129_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdstatement',
            name='signer_authorized',
            field=models.BooleanField(default=False, null=True, verbose_name='Signer Authorization'),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='signer_authorized',
            field=models.BooleanField(default=False, null=True, verbose_name='Signer Authorization'),
        ),
    ]
