# Generated by Django 2.1.1 on 2018-12-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0019_auto_20181129_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdstatement',
            name='ed_uploaded',
            field=models.TextField(default='empty', help_text='SAML EntityDescriptor (geladen, nicht signiert)', max_length=100000, verbose_name='EntityDescriptor hochgeladen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='ed_uploaded',
            field=models.TextField(default='empty', help_text='SAML EntityDescriptor (geladen, nicht signiert)', max_length=100000, verbose_name='EntityDescriptor hochgeladen'),
            preserve_default=False,
        ),
    ]
