# Generated by Django 2.1.1 on 2018-12-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0020_auto_20181202_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdstatement',
            name='make_blank_entityid_unique',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='if the entityID is blank due to a validation error, this hash value assures that the unique constraint is not violated'),
        ),
        migrations.AddField(
            model_name='mdstatement',
            name='statusgroup',
            field=models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend')], default='frontend', max_length=8, verbose_name='Status Group'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='make_blank_entityid_unique',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='if the entityID is blank due to a validation error, this hash value assures that the unique constraint is not violated'),
        ),
        migrations.AddField(
            model_name='mdstatementhistory',
            name='statusgroup',
            field=models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend')], default='frontend', max_length=8, verbose_name='Status Group'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='content_valid',
            field=models.BooleanField(default=False, verbose_name='Content validation'),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='namespace',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mdstatement',
            name='status',
            field=models.CharField(choices=[('created', 'erstellt'), ('uploaded', 'hochgeladen'), ('signed', 'signiert'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('accepted', 'akzeptiert')], default='created', max_length=14, verbose_name='Workflow Status'),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='content_valid',
            field=models.BooleanField(default=False, verbose_name='Content validation'),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='namespace',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='status',
            field=models.CharField(choices=[('created', 'erstellt'), ('uploaded', 'hochgeladen'), ('signed', 'signiert'), ('request_queue', 'signiert und eingebracht'), ('rejected', 'fehlerhaft'), ('accepted', 'akzeptiert')], default='created', max_length=14, verbose_name='Workflow Status'),
        ),
        migrations.AlterUniqueTogether(
            name='mdstatement',
            unique_together={('entityID', 'make_blank_entityid_unique', 'statusgroup')},
        ),
    ]
