# Generated by Django 2.1.1 on 2018-12-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaladmin', '0021_auto_20181202_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdstatement',
            name='statusgroup',
            field=models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend')], max_length=8, verbose_name='Status Group'),
        ),
        migrations.AlterField(
            model_name='mdstatementhistory',
            name='statusgroup',
            field=models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend')], max_length=8, verbose_name='Status Group'),
        ),
    ]
